### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fsantanderb** [lucky-luk3/Grafiki#8]
**./setup.sh** ends with the following error:

Collecting djangorestframework
  Downloading djangorestframework-3.14.0-py3-none-any.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 5.3 MB/s 
Collecting django-crispy-forms
  Downloading django_crispy_forms-1.14.0-py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 26.9 MB/s 
**ERROR: Could not find a version that satisfies the requirement evtx==0.6.7
ERROR: No matching distribution found for evtx==0.6.7**

**Comment by lucky-luk3** [comment]
@fsantanderb thanks for opening this issue.
Now it is fixed and changed the installation process to Docker.
Let me know if something goes wrong please.
